# fly.toml app configuration file generated for game-store on 2023-08-08T20:27:39-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "game-store"
primary_region = "eze"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
